#!/bin/bash
#SBATCH --partition       sugon
#SBATCH --time            10-00:00:00
#SBATCH --nodes           2
#SBATCH --ntasks-per-node 16
#SBATCH --cpus-per-task   1
#SBATCH --error           out_%j.err
#SBATCH --output          out_%j.log

ulimit -s unlimited
#export I_MPI_PMI_LIBRARY=libpmi2.so

module purge
module load oneAPI/2021.2.0 mpi/intel/2021.2.0 
module load anaconda3/2023.03
source /public/apps/anaconda/anaconda3/2023.03/etc/profile.d/conda.sh
conda activate schnet

echo "============================================================"
module list
env | grep "MKLROOT="
echo "============================================================"
echo "Job ID: $SLURM_JOB_NAME"
echo "Job name: $SLURM_JOB_NAME"
echo "Number of nodes: $SLURM_JOB_NUM_NODES"
echo "Number of processors: $SLURM_NTASKS"
echo "Task is running on the following nodes:"
echo $SLURM_JOB_NODELIST
echo "OMP_NUM_THREADS = $SLURM_CPUS_PER_TASK"
echo "============================================================"
echo

#srun /public/home/jiangx/paraNAMD/0.0.4/HFNAMD
python predict.py
